sample-output.txt: sample-input.txt
	cat sample-input.txt | lookup -f tfeatures.scr > sample-output.txt

# The above command gives morphological features in the output.
# One can also use:
#	cat sample-input.txt | lookup -f tlexical.scr > sample-output.txt
#	cat sample-input.txt | lookup -f tlexmorph.scr > sample-output.txt
# For alternative output features.
